@echo off
echo Adding changes...
git add .
echo Committing changes...
git commit -m "feat: use color palette for blocks, hide habit progress from home page and display on management tabs"
echo Pushing to GitHub...
git push
echo Done!
pause
